# -*- coding: utf-8 -*-
"""atm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HYpgGs_Ra66ygbyWJvFdub60nHtahxYZ
"""

# Install ipywidgets if not installed
!pip install ipywidgets

import ipywidgets as widgets
from IPython.display import display, clear_output

# Initialize PIN and balance
USER_PIN = "1234"
balance = 5000

# Output widget to display messages
output = widgets.Output()

# Function to check PIN
def check_pin(btn):
    clear_output(wait=True)
    entered_pin = pin_input.value
    if entered_pin == USER_PIN:
        main_menu()
    else:
        with output:
            print("❌ Incorrect PIN! Try again.")
        display(ui)

# Function to display main menu
def main_menu():
    clear_output(wait=True)
    display(widgets.Label("===== ATM MENU ====="))
    check_balance_btn = widgets.Button(description="Check Balance")
    deposit_btn = widgets.Button(description="Deposit Money")
    withdraw_btn = widgets.Button(description="Withdraw Money")
    exit_btn = widgets.Button(description="Exit")

    # Connect buttons to functions
    check_balance_btn.on_click(check_balance)
    deposit_btn.on_click(deposit_money)
    withdraw_btn.on_click(withdraw_money)
    exit_btn.on_click(exit_atm)

    menu_ui = widgets.VBox([check_balance_btn, deposit_btn, withdraw_btn, exit_btn, output])
    display(menu_ui)

# Check Balance function
def check_balance(btn):
    clear_output(wait=True)
    global balance
    with output:
        print(f"Your current balance is: ₹{balance}")
    main_menu()

# Deposit Money function
def deposit_money(btn):
    clear_output(wait=True)
    amount_input = widgets.FloatText(description="Amount: ₹")
    submit_btn = widgets.Button(description="Deposit")

    def deposit_submit(btn):
        global balance
        amount = amount_input.value
        if amount > 0:
            balance += amount
            with output:
                print(f"₹{amount} deposited successfully! Current balance: ₹{balance}")
        else:
            with output:
                print("❌ Invalid deposit amount!")
        main_menu()

    submit_btn.on_click(deposit_submit)
    display(widgets.VBox([amount_input, submit_btn, output]))

# Withdraw Money function
def withdraw_money(btn):
    clear_output(wait=True)
    amount_input = widgets.FloatText(description="Amount: ₹")
    submit_btn = widgets.Button(description="Withdraw")

    def withdraw_submit(btn):
        global balance
        amount = amount_input.value
        if amount <= 0:
            with output:
                print("❌ Invalid withdrawal amount!")
        elif amount > balance:
            with output:
                print("❌ Insufficient balance!")
        else:
            balance -= amount
            with output:
                print(f"₹{amount} withdrawn successfully! Remaining balance: ₹{balance}")
        main_menu()

    submit_btn.on_click(withdraw_submit)
    display(widgets.VBox([amount_input, submit_btn, output]))

# Exit function
def exit_atm(btn):
    clear_output(wait=True)
    print("✅ Thank you for using the ATM. Goodbye!")

# PIN input widget
pin_input = widgets.Password(description="Enter PIN:")
submit_pin = widgets.Button(description="Login")
submit_pin.on_click(check_pin)

ui = widgets.VBox([pin_input, submit_pin, output])
display(ui)